### ISSUE TITLE
starting server fails (stack trace)

### ISSUE THREAD

**Issue by jb08** [scalatra/scalatra-website#134]
starting server fails with this error. I noticed in the _config, and in the most recent commit of Dec-16, that this webstie documentation seems old. Is this still the current [scalatra.org](http://scalatra.org/)?

```
ch-nb-1614:scalatra-website$ jekyll --server --auto
/Users/jbrown/.gem/ruby/2.3.1/gems/liquid-2.5.0/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Configuration from /Users/jbrown/Documents/Repos/scalatra-website/_config.yml
/Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- sass/script/node (LoadError)
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/jbrown/.gem/ruby/2.3.1/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jbrown/.gem/ruby/2.3.1/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
	from /Users/jbrown/.gem/ruby/2.3.1/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
	from /Users/jbrown/.gem/ruby/2.3.1/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jbrown/.rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jbrown/.gem/ruby/2.3.1/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
```

**Comment by takezoe** [comment]
Current web site is built using [hugo](https://gohugo.io/) from this branch: https://github.com/scalatra/scalatra-website/tree/feature/hugo

**Comment by treaz** [comment]
@jb08 is this still an issue? Can we close it?
